version: "2"
services:
  web:
    image: node
    working_dir: /app
    command: node start.js
    ports:
      - "3000:3000"
    links:
      - database
    environment:
      DB_HOST: database
      DB_USER: kanban
      DB_PASS: kanban
      DB_NAME: kanban
    depends_on:
      - database
    volumes:
      - .:/app
  database:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: kanban
      MYSQL_USER: kanban
      MYSQL_PASSWORD: kanban
    volumes:
      - data:/var/lib/mysql
      - ./data:/docker-entrypoint-initdb.d
volumes:
  data: